shard.yml
spec/bindgen/config_reader/loader_spec.cr
spec/clang/spec_helper.cr
src/bindgen/library.cr
src/bindgen/parser/runner.cr
src/bindgen/processor/instantiate_containers.cr
tool.sh

Use `File.tempfile` instead, works pretty much just the same. 
Hopefully this'll resolve https://github.com/Papierkorb/qt5.cr/issues/21.

WIP: Remove Tempfile as it was removed in crystal .27

---

shard.yml
spec/bindgen/config_reader/loader_spec.cr
spec/clang/spec_helper.cr
src/bindgen/library.cr
src/bindgen/parser/runner.cr
src/bindgen/processor/instantiate_containers.cr
tool.sh

There is still one issue that remains, when running the specs:
```
Failures:
1) clang tool macros feature exports the macros
At macros.10.evaluated: Expected 9223372036854775808_u64, got -9223372036854775808_i64 (ClangValidationError)
from /spec_helper.cr:79:91 in 'check_partial_value'
from /spec_helper.cr:64:7 in 'check_partial_value'
from /spec_helper.cr:75:7 in 'check_partial_value'
from spec/clang/spec_helper.cr:31:5 in 'clang_tool:macros'
from spec/clang/macros_spec.cr:5:5 in '->'
from /usr/share/crystal/src/spec/methods.cr:255:3 in 'it'
from spec/clang/macros_spec.cr:4:3 in '->'
from /usr/share/crystal/src/spec/context.cr:255:3 in 'describe'
from /usr/share/crystal/src/spec/methods.cr:16:5 in 'describe'
from spec/integration/spec_helper.cr:1:1 in '__crystal_main'
from …
```

Fixes for breaking changes in Crystal

---

src/bindgen/generator/crystal.cr
src/bindgen/processor/enums.cr

Some notes:
+ method `#capitalize` will turn `Dead_A` to `Dead_a`, so removed;
+ doing `#{name.camelcase}` in src/bindgen/generator/crystal.cr is useless,
as it will be done in Enums#camelcase_fields

final fix for issue #6

---

clang/CMakeLists.txt
clang/find_clang.cr

This is for #28 and also fixes a few issues i saw with the cmake script:
- added cli parsing to find_clang.cr
- fixed issue where llvm_libs were blank
- fixed an issue where find_clang would fail silently in cmake
I added support for a `--clang` flag to the `find_clang.cr` script, which will allow definition of which clang to use. This fixed a lot of problems since cmake can pass it.

Clang 10 Support

---

builtin_types.yml
src/bindgen/call_builder/crystal_wrapper.cr

This change forces method argument for `unsafe_fetch` to be `Int` type.

fix for error "#unsafe_fetch(index : Int)` must be implemented ..."

---

clang/find_clang.cr

fetch all paths after `-internal-isystem` flag until next flag

---

src/bindgen/processor/enums.cr

Ensure that enum value name is started with uppercase letter.
Before this change code could produce invalid crystal code.
Sorry that I didn't fix this at once.

Always start enum value name with uppercase letter

---

clang/CMakeLists.txt

`GREATER_EQUAL` was introduced in CMake 3.7 but Travis is still using 3.5.1, so `GREATER` should be used instead.

Fix CI for old CMake versions

---

clang/CMakeLists.txt

`CMAKE_CXX_STANDARD_xx` -> `CMAKE_CXX_STANDARD xx`

CI: Fix "use of undeclared identifier 'nullptr'"

---

README.md
SPEC.md
TEMPLATE.yml
spec/integration/qt.cpp
spec/integration/qt.yml
spec/integration/qt_spec.cr
src/bindgen/call.cr
src/bindgen/crystal/format.cr
src/bindgen/processor/block_overloads.cr
src/bindgen/processor/sanity_check.cr

An attempt to fix #59, through a new `BlockOverloads` processor. For instance this is `Qt::ButtonGroup#on_button_toggled`, which has 2 overloads each taking two parameters in the block:
```crystal
module Qt
class ButtonGroup
def on_button_toggled(_type1_ : AbstractButton.class, _type2_ : Bool.class, &_proc_ : Proc(AbstractButton, Bool, Void)) : SignalConnection
SignalConnection.new(unwrap: Binding.bg_QButtonGroup_CONNECT_buttonToggled_CrystalProc_void_QAbstractButton_X_bool(self, BindgenHelper.wrap_proc(_proc_)))
end
def on_button_toggled(_type1_ : Int32.class, _type2_ : Bool.class, &_proc_ : Proc(Int32, Bool, Void)) : SignalConnection
SignalConnection.new(unwrap: Binding.bg_QButtonGroup_CONNECT_buttonToggled_CrystalProc_void_int_bool(self, BindgenHelper.wrap_proc(_proc_)))
end
end
end …
```

Add type tags for block parameter disambiguation

---

src/bindgen/processor/sanity_check.cr

This small patch makes Bindgen's handling of flag-enums closer to Crystal's:
* `None` is [allowed](https://github.com/crystal-lang/crystal/blob/099b9ecc28f6ee015718c140ef2d62566876d675/spec/compiler/semantic/enum_spec.cr#L201) as long as its value is 0. Some Qt flags actually do this, for example [`QStyleOptionButton::ButtonFeatures`](https://doc.qt.io/qt-5/qstyleoptionbutton.html#ButtonFeature-enum).
* Flag-enums that only contain `None` are [disallowed](https://github.com/crystal-lang/crystal/blob/099b9ecc28f6ee015718c140ef2d62566876d675/spec/compiler/semantic/enum_spec.cr#L392).

SanityCheck: more accurate rules for enum None

---

spec/bindgen/graph/path_spec.cr
src/bindgen/graph/builder.cr
src/bindgen/graph/path.cr
src/bindgen/processor/crystal_wrapper.cr
src/bindgen/processor/inheritance.cr
src/bindgen/processor/sanity_check.cr
src/bindgen/util.cr

This fixes all the issues in #80, makes local lookup more robust, and handles nested generic names.
I also added a `Path#join` method, since there are a few places in the source code where I would like to replace strings with paths. `Path.from` is now based on `#join` as well.

Improve Graph::Path

---

spec/bindgen/processor/extern_c_spec.cr
spec/bindgen/template_spec.cr
src/bindgen/call.cr
src/bindgen/call_builder/cpp_call.cr
src/bindgen/call_builder/cpp_qobject_connect.cr
src/bindgen/call_builder/cpp_to_crystal_proc.cr
src/bindgen/call_builder/crystal_binding.cr
src/bindgen/call_builder/crystal_from_cpp.cr
src/bindgen/call_builder/crystal_superclass.cr
src/bindgen/call_builder/crystal_superclass_init.cr
src/bindgen/call_builder/crystal_wrapper.cr
src/bindgen/cpp/cookbook.cr
src/bindgen/cpp/pass.cr
src/bindgen/crystal/pass.cr
src/bindgen/crystal/typename.cr
src/bindgen/processor/crystal_binding.cr
src/bindgen/processor/crystal_wrapper.cr
src/bindgen/processor/extern_c.cr
src/bindgen/processor/instance_properties.cr
src/bindgen/processor/instantiate_containers.cr
src/bindgen/processor/virtual_override.cr
src/bindgen/template.cr
src/bindgen/template/base.cr
src/bindgen/template/basic.cr
src/bindgen/template/none.cr
src/bindgen/template/proc_from_wrapper.cr
src/bindgen/template/sequence.cr
src/bindgen/type_database.cr
src/bindgen/type_helper.cr
src/bindgen/util.cr

This patch, split from #78, promotes conversion templates (`Bindgen::Call::Result#conversion`) to their own class hierarchy. This allows templates to perform complex substitutions that `Util.template` cannot achieve.
The main issue with `Util.template` is that it only supports simple string substitutions (e.g. `%.to_unsafe`, `Converter.unwrap(%)`). Passing a wrapper-`Proc` to a `CrystalProc` is an example that cannot be expressed in this way:
* The binding expects a binding-`Proc`, which takes binding types and returns a binding type;
* The user-provided wrapper-`Proc` takes and returns wrapper types.
* Thus, the binding-`Proc` needs to convert each argument to its wrapper type, invoke `_proc_`, then convert the return value to its binding type;
* The binding-`Proc` _itself_ needs to be …

Refactor conversion templates into classes

---

spec/integration/qt.cpp
spec/integration/qt.yml
spec/integration/qt_spec.cr
src/bindgen/call_builder/cpp_qobject_connect.cr
src/bindgen/call_builder/cpp_to_crystal_proc.cr
src/bindgen/crystal/pass.cr
src/bindgen/processor/qt.cr
src/bindgen/processor/virtual_override.cr

#78, but without the template-related commits.

Fix Proc argument conversions when passing to binding (again)

---

clang/include/bindgen_ast_consumer.hpp
clang/include/bindgen_frontend_action.hpp
clang/include/enum_match_handler.hpp
clang/include/function_match_handler.hpp
clang/include/helper.hpp
clang/include/json_stream.hpp
clang/include/preprocessor_handler.hpp
clang/include/record_match_handler.hpp
clang/include/structures.hpp
clang/src/bindgen_ast_consumer.cpp
clang/src/bindgen_frontend_action.cpp
clang/src/enum_match_handler.cpp
clang/src/function_match_handler.cpp
clang/src/preprocessor_handler.cpp
clang/src/record_match_handler.cpp
clang/src/structures.cpp

This refactor brings the equivalent of Crystal's `Bindgen::Parser::Document` to the Clang parser.
Alone it doesn't do anything new, but passing the whole document around allows each registered AST handler to insert multiple parser values (there will be a use case for this).

Document type for the Clang parser

---

TEMPLATE.yml
clang/src/record_match_handler.cpp
spec/integration/inheritance.cpp
spec/integration/inheritance.yml
spec/integration/inheritance_spec.cr
spec/integration/virtual_override.yml
spec/integration/virtual_override_spec.cr
src/bindgen/generator/cpp.cr
src/bindgen/parser/base_class.cr
src/bindgen/processor/sanity_check.cr
src/bindgen/processor/virtual_override.cr
src/bindgen/type_database.cr

Fixes #67. More specifically,
* The Clang parser now reports inheritance relations using fully qualified names. This allows Bindgen to pick up inherited classes in namespaces.
* Binding type names are guaranteed not to include `::`, by replacing them with underscores.
* C++ `BgInherit` structs now inherit constructors of namespaced types properly.
* The names of `BgJumptable` and `BgInherit` structs now include any enclosing namespaces of the C++ types (because these structs are all emitted to the top-level C++ namespace).
A consequence of these fixes is that namespaced types can be mapped directly:
```yaml
classes:
Module::Super: Module::Super
types:
```
I have also confirmed that this doesn't break qt5.cr (it merely removes a bunch of redundant `Binding::`s under `lib Binding`).

Better namespace resolution for namespaced types

---

clang/include/json_stream.hpp
clang/include/structures.hpp

Follow-up to #84.
Some processors rely on the object key order of the JSON document generated by the Clang parser; most notably, the Crystal wrapper generators assume that every class appears before its subclasses, so that subclasses never inherit from undefined base classes. This class order is directly derived from the Clang parser. However, using `std::map` means the keys are always sorted in alphabetical order, so code like below breaks because `A` will be added to the JSON before `B`:
```cpp
struct B { };
struct A : B { };
```
```crystal
class A < B
end
class B
end
```
The simplest fix is to use a custom `std::map`-like container in the `Document` struct that keeps track of the key insertion order. This patch requires no changes on the Crystal side.

Regression: maintain object key order of parser document JSON

---

SPEC.md
clang/include/structures.hpp
clang/src/record_match_handler.cpp
clang/src/structures.cpp
spec/integration/copy_structs.cpp
spec/integration/copy_structs.yml
spec/integration/copy_structs_spec.cr
spec/integration/instance_properties.yml
spec/integration/instance_properties_spec.cr
src/bindgen/generator/crystal_lib.cr
src/bindgen/graph/class.cr
src/bindgen/graph/cpp_union.cr
src/bindgen/graph/struct.cr
src/bindgen/graph/visitor.cr
src/bindgen/parser/class.cr
src/bindgen/parser/type.cr
src/bindgen/parser/type_kind.cr
src/bindgen/processor/copy_structs.cr
src/bindgen/processor/function_class.cr
src/bindgen/processor/inheritance.cr
src/bindgen/processor/instance_properties.cr
src/bindgen/processor/virtual_override.cr

C `union`s are distinct from Crystal `Union`s for a few reasons:
* C `union`s are a layout constraint that associates names to each variant member; Crystal `Union`s are a type constraint and cannot do the same.
* C `union`s may use repeated types among variant members, like `button` and `axis` below.
* It is well-defined in C to write to a variant member of a `union` and then read from a different variant member. (This is undefined behaviour in C++ but most compilers use the C behaviour anyway.)
This patch allows C `union`s to have their structures copied or their instance property methods generated. Nested structures are also handled properly. After this PR, a compound structure like
```cpp
typedef struct SDL_GameControllerButtonBind
{
SDL_GameControllerBindType bindType;
union
{
int …
```

Add support for C unions

---

spec/integration/containers.cpp
spec/integration/containers.yml
spec/integration/containers_spec.cr
src/bindgen/cpp/pass.cr
src/bindgen/cpp/typename.cr
src/bindgen/processor/instantiate_containers.cr

This small patch ensures that template type names generated by Bindgen in some places do not contain `>>`, to match the Clang parser's output; for example, `std::vector<std::vector<int> >` would be used instead of `std::vector<std::vector<int>>`. It seems this is all it takes to support those nested container types; before this the integration test would fail with an invalid `lib` alias.
The other alternative is to alter the parser itself so that it doesn't add spaces between the `>`s, which are no longer required in C++11. Clang provides [`clang::PrintingPolicy::SplitTemplateClosers`](https://clang.llvm.org/doxygen/structclang_1_1PrintingPolicy.html#a1aa9b0aa468f6669be43c75ebd087ed3), but this doesn't seem to be available on Clang 9 (which I use).

Allow instantiations of nested container types

---

SPEC.md
clang/include/enum_match_handler.hpp
clang/include/structures.hpp
clang/src/enum_match_handler.cpp
clang/src/record_match_handler.cpp
clang/src/structures.cpp
spec/integration/enums.cpp
spec/integration/enums.yml
spec/integration/enums_spec.cr
src/bindgen/parser/enum.cr
src/bindgen/processor/enums.cr

This PR adds support for nested constants defined in the form of anonymous enums:
```cpp
struct A {
enum { X, Y, Z };
};
```
```crystal
class A
X = 0u32
Y = 1u32
Z = 2u32
end
```
Such constructs are sometimes seen in C++ code to define compile-time constants, instead of `static const`. Qt uses it for [`QGraphicsItem::type()`](https://doc.qt.io/qt-5/qgraphicsitem.html#anonymous-enum).
This PR does not address the use of anonymous enumerators in instance variables.

Host anonymous enumerators inside wrapped classes as constants

---

README.md
SPEC.md
TEMPLATE.yml
clang/include/record_match_handler.hpp
clang/include/structures.hpp
clang/src/record_match_handler.cpp
clang/src/structures.cpp
clang/src/type_helper.cpp
spec/integration/copy_structs.cpp
spec/integration/copy_structs_spec.cr
spec/integration/instance_properties_spec.cr
src/bindgen/call_builder/crystal_abstract_def.cr
src/bindgen/call_builder/crystal_wrapper.cr
src/bindgen/cpp/method_name.cr
src/bindgen/crystal/format.cr
src/bindgen/crystal/type.cr
src/bindgen/graph/method.cr
src/bindgen/graph/struct.cr
src/bindgen/parser/argument.cr
src/bindgen/parser/class.cr
src/bindgen/parser/field.cr
src/bindgen/parser/method.cr
src/bindgen/processor/copy_structs.cr
src/bindgen/processor/inheritance.cr
src/bindgen/processor/instance_properties.cr
src/bindgen/processor/sanity_check.cr
src/bindgen/type_database.cr

Generates getters and setters for static variables, just like instance variables. Considerable portions of the changes are just documentation changes to reflect that both static and non-static data members are supported.
```cpp
struct Application {
static Application *instance;
static const int VERSION = 103;
};
Application *Application::instance = /* ... */;
```
produces:
```cpp
extern "C" Application * bg_Application_instance_STATIC_GETTER_() {
return Application::instance;
}
extern "C" void bg_Application_instance_STATIC_SETTER_Application_X(Application * instance) {
Application::instance = instance;
}
extern "C" const int bg_Application_VERSION_STATIC_GETTER_() {
return Application::VERSION;
}
```
```crystal
module Test
lib Binding
alias Application = Void
fun …
```

Generate property methods / constants for static data members

---

assets/glue.cr
src/bindgen/generator/crystal.cr
src/bindgen/graph/class.cr
src/bindgen/processor/instantiate_containers.cr

Turns `BindgenHelper::SequentialContainer` into a module. This serves two purposes:
* It prevents Crystal from reducing unions of possibly unrelated containers into `SequentialContainer`.
* It frees up the Crystal base class so that actual inheritance of container wrappers can be represented, should it be done in the future (e.g. `Container_QQueue_int < Container_QList_int`).

Use module instead of abstract base class for instantiated containers

---

README.md
SPEC.md
TEMPLATE.yml
clang/include/structures.hpp
clang/src/record_match_handler.cpp
clang/src/structures.cpp
spec/integration/basic.cpp
spec/integration/basic.yml
spec/integration/basic_spec.cr
src/bindgen/call_builder/cpp_call.cr
src/bindgen/crystal.cr
src/bindgen/parser/class.cr
src/bindgen/parser/method.cr
src/bindgen/processor.cr
src/bindgen/processor/filter_methods.cr
src/bindgen/processor/operators.cr
src/bindgen/processor/sanity_check.cr

Wraps a lot of overloaded operators, provided they are defined inside a C++ class body. Some operators cannot be overloaded in Crystal (most notably the compound assignments), so they are renamed to normal methods containing `!` in their names, see SPEC.md for the list of renamings. A few details have been left out for separate PRs in the future:
* Non-member overloaded operators can be parsed, but the general case requires reopening core Crystal classes if the left operand is not a wrapped class, e.g. [`QVector3D` multiplication](https://doc.qt.io/qt-5/qvector3d.html#operator-2a).
* `operator=` needs special care, due to its relation with copy constructors. It would probably be called `assign!`.
* Although not limited to operators, `operator[]` usually has both non-const and const …

Support most overloaded member operators

---

assets/glue.cr

`abstract def push(value)` without the type restriction on `value` will no longer work as of crystal-lang/crystal@d44530d, which produces errors such as
```
In tmp/containers.cr:65:20
65 | abstract def push(value)
^---
Error: abstract `def Test::BindgenHelper::SequentialContainer(T)#push(value)` must be implemented by Test::Container_std__vector_int
```

Regression: require SequentialContainer(T)#push to accept value of type T

---

spec/bindgen/parser/type_spec.cr
src/bindgen/parser/argument.cr
src/bindgen/parser/method.cr
src/bindgen/parser/type.cr
src/bindgen/parser/type/cpp_type_parser.cr

Extends Bindgen's type parser to handle C++ templates, and adds methods that replace names in a given type with other types. This PR lays the groundwork for at least 2 scenarios:
* Alias resolution, including in template arguments, e.g. from `const QVector<QRgb> &` to `const QVector<unsigned int> &`, provided `QRgb` is an alias for `unsigned int`. This can be used for the first issue mentioned in #102; before this PR, the most Bindgen could do was resolving one level of aliases in each template argument.
* Template type substitution, e.g. `QVector<const T *>` to `QVector<const QVector<int> *>`, provided `T` is instantiated with `const QVector<int> &` (notice the combination of const-ness and references and pointers). This allows for example the possibility of defining container interfaces …

Support type substitution of template types

---

builtin_types.yml
clang/src/type_helper.cpp
spec/bindgen/type_database_spec.cr
src/bindgen/cpp/pass.cr
src/bindgen/crystal/pass.cr
src/bindgen/parser/argument.cr
src/bindgen/parser/class.cr
src/bindgen/parser/method.cr
src/bindgen/parser/type.cr
src/bindgen/processor/function_class.cr
src/bindgen/processor/instantiate_containers.cr
src/bindgen/processor/virtual_override.cr
src/bindgen/type_database.cr

Improves alias resolution of type names.
After a new alias is added, any internal aliases among the aliases' underlying types are immediately resolved; an alias then becomes recursive only if it refers to its own name. Bindgen now reports recursive aliases on addition, including loops and indirect recursions like `T` -> `const T *` or `std::vector<T>`. Alias resolution for user types is also faster, since type substitution occurs exactly once (in `TypeDatabase#resolve_aliases`).
For this to work correctly across various scenarios, even more `Parser::Type` objects have their full type names canonicalized:
* `#template` always refers to the type name's template arguments. Before this PR, the Clang parser would report types like `std::string` that don't have a template argument list, but …

Better support for recursive aliases

---

SPEC.md
clang/include/bindgen_ast_consumer.hpp
clang/include/json_stream.hpp
clang/include/operator_match_handler.hpp
clang/src/bindgen_ast_consumer.cpp
clang/src/operator_match_handler.cpp
spec/integration/basic.cpp
spec/integration/basic.yml
spec/integration/basic_spec.cr

Wraps overloaded operators that are not instance methods, as long as their first parameter accepts a wrapped type by (non-const or const) lvalue reference. The operators are transformed into methods by the Clang parser entirely; it makes no differences to Bindgen whether a given operator was defined as a method or not.
On Qt5.cr this mainly affects the geometric object types (`QLine`, `QRect`, `QPolygon`, `QTransform`, and so on).

Support non-member overloaded operators

---

SPEC.md
clang/find_clang.cr
spec/integration/containers.cpp
spec/integration/containers.yml
spec/integration/containers_spec.cr
src/bindgen/configuration.cr
src/bindgen/cpp/method_name.cr
src/bindgen/processor/auto_container_instantiation.cr
src/bindgen/processor/instantiate_containers.cr
src/bindgen/processor/sanity_check.cr
src/bindgen/type_database.cr

This PR adds support for two kinds of aliases:
* Aliased names inside template type arguments, e.g. `QVector<QRgb>` now resolves properly to `QVector<unsigned int>`. Both C++ types will use the same wrapper, so the former container is no longer instantiated separately, as required by #102.
* Aliases to container instantiations, e.g. `QObjectList` now resolves properly to `QList<QObject *>`. Consequently, the wrapper for `QObject::children()` will no longer return a raw pointer to the container after this PR, as long as the appropriate alias is defined in the config file:
```yaml
types:
QObjectList: { alias_for: "QList<QObject *>" }
```
Due to recent changes, the type database now has separate rule entries for actual C++ containers (e.g. `QList<QWindow *>`) and their template-less aliases …

Automatically instantiate aliased container templates

---

TEMPLATE.yml
assets/bindgen_helper.hpp
src/bindgen/cpp/cookbook.cr

All C++ class instances are wrapped in a `CrystalGCWrapper` class
that ensures that the garbage collector calls the destructor.
Fixes issue #86.

Wrap C++ classes so that the destructor is called.

---

assets/bindgen_helper.hpp
src/bindgen/cpp/method_name.cr
src/bindgen/crystal/argument.cr
src/bindgen/generator/crystal.cr
src/bindgen/processor/crystal_wrapper.cr

The goal of this PR is to support "struct-like", i.e. value-like, *classes*. An example are classes like `QPoint` or `QSize` from Qt. These types are effectively small pass-by-value structs. The current bindgen implementation generates fully heap-allocated classes for them. However, this puts huge pressure on the memory allocator/garbage collector if used in a tight loop, e.g. using `QPoint` in a `paint_event` (and sometimes using theses classes is obligatory). For this reason the current qt5.cr implementation has a *manual* wrapper around `QPoint` (but not `QRect`, `QSize`, `QLine`).
Bindgen is actually able to generate wrapper code for structs but not for methods (especially constructors) within those structs. The purpose of this PR is to handle this case. The following important …

Fix non-pointer constructors for struct like types.
